"""Add photo_path to todos

Revision ID: 1e4f8bed4a98
Revises: e132c38f97ff
Create Date: 2024-07-08 21:51:56.581973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4f8bed4a98'
down_revision = 'e132c38f97ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'photo_path')
    # ### end Alembic commands ###
