"""change realtionships

Revision ID: 783280ca80f8
Revises: 8132e7dbbbc6
Create Date: 2024-07-15 11:07:41.112684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783280ca80f8'
down_revision: Union[str, None] = '8132e7dbbbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_photos')
    op.alter_column('photos', 'todo_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.add_column('todos', sa.Column('comany_name', sa.String(), nullable=True))
    op.alter_column('todos', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('todos', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'todos', 'companies', ['comany_name'], ['name'])
    op.add_column('users', sa.Column('comany_name', sa.String(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'companies', ['comany_name'], ['name'])
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'comany_name')
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.alter_column('todos', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('todos', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('todos', 'comany_name')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.alter_column('photos', 'todo_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('_alembic_tmp_photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('todo_id', sa.NUMERIC(), nullable=True),
    sa.Column('photo_path', sa.VARCHAR(), nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
