"""Update Todos model to use single assignee_id

Revision ID: cd9526741d3d
Revises: b3617d076bdf
Create Date: 2024-08-06 20:16:47.390984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd9526741d3d'
down_revision: Union[str, None] = 'b3617d076bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'todos', 'users', ['assignee_id'], ['id'])
    op.drop_column('todos', 'assignee_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('assignee_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'assignee_id')
    # ### end Alembic commands ###
