"""Create User and Task models

Revision ID: e132c38f97ff
Revises: 
Create Date: 2024-07-07 11:22:39.360627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e132c38f97ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()'), index=True),
        sa.Column('email', sa.String, unique=True),
        sa.Column('username', sa.String, unique=True),
        sa.Column('firstname', sa.String),
        sa.Column('lastname', sa.String),
        sa.Column('hashed_password', sa.String),
        sa.Column('isactive', sa.Boolean, default=True),
        sa.Column('role', sa.String),
        sa.Column('icon', sa.String)
    )
    op.create_table('todos',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()'), index=True),
        sa.Column('title', sa.String),
        sa.Column('body', sa.String),
        sa.Column('color', sa.String),
        sa.Column('status', sa.String),
        sa.Column('deadline', sa.DateTime, nullable=True),
        sa.Column('remainder', sa.Boolean, default=True),
        sa.Column('owner_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('users')
    # ### end Alembic commands ###
